from aiogram.types import InlineKeyboardButton, InlineKeyboardMarkup

ikb = InlineKeyboardMarkup(row_width=4)
ib1 = InlineKeyboardButton(text='Африкаанс', callback_data='af')
ib2 = InlineKeyboardButton(text='Амхарский', callback_data='am')
ib3 = InlineKeyboardButton(text='Арабский', callback_data='ar')
ib4 = InlineKeyboardButton(text='Азербайджанский', callback_data='az')
ib5 = InlineKeyboardButton(text='Башкирский', callback_data='ba')
ib6 = InlineKeyboardButton(text='Белорусский', callback_data='be')
ib7 = InlineKeyboardButton(text='Болгарский', callback_data='bg')
ib8 = InlineKeyboardButton(text='Бенгальский', callback_data='bn')
ib9 = InlineKeyboardButton(text='Боснийский', callback_data='bs')
ib10 = InlineKeyboardButton(text='Каталанский', callback_data='ca')
ib11 = InlineKeyboardButton(text='Чешский', callback_data='cs')
ib12 = InlineKeyboardButton(text='Чувашский', callback_data='cv')
ib13 = InlineKeyboardButton(text='Валийский', callback_data='cy')
ib14 = InlineKeyboardButton(text='Датский', callback_data='da')
ib15 = InlineKeyboardButton(text='Немецкий', callback_data='de')
ib16 = InlineKeyboardButton(text='Греческий', callback_data='el')
ib17 = InlineKeyboardButton(text='Английский', callback_data='en')
ib18 = InlineKeyboardButton(text='Эсперанто', callback_data='eo')
ib19 = InlineKeyboardButton(text='Испанский', callback_data='es')
ib20 = InlineKeyboardButton(text='Эстонский', callback_data='et')
ib21 = InlineKeyboardButton(text='Баскский', callback_data='eu')
ib22 = InlineKeyboardButton(text='Персидиский', callback_data='fa')
ib23 = InlineKeyboardButton(text='Финский', callback_data='fi')
ib24 = InlineKeyboardButton(text='Французский', callback_data='fr')
ib25 = InlineKeyboardButton(text='Ирландский', callback_data='ga')
ib26 = InlineKeyboardButton(text='Шотландский', callback_data='gd')
ib27 = InlineKeyboardButton(text='Галисийский', callback_data='gl')
ib28 = InlineKeyboardButton(text='Гуджарати', callback_data='gu')
ib29 = InlineKeyboardButton(text='Иврит', callback_data='he')
ib30 = InlineKeyboardButton(text='Хинди', callback_data='hi')
ib31 = InlineKeyboardButton(text='Хорватский', callback_data='hr')
ib32 = InlineKeyboardButton(text='Гаитянский', callback_data='ht')
ib33 = InlineKeyboardButton(text='Венгерский', callback_data='hu')
ib34 = InlineKeyboardButton(text='Армянский', callback_data='hy')
ib35 = InlineKeyboardButton(text='Индонезийский', callback_data='id')
ib36 = InlineKeyboardButton(text='Исландский', callback_data='is')
ib37 = InlineKeyboardButton(text='Итальянский', callback_data='it')
ib38 = InlineKeyboardButton(text='Японский', callback_data='ja')
ib39 = InlineKeyboardButton(text='Яванский', callback_data='jv')
ib40 = InlineKeyboardButton(text='Грузинский', callback_data='ka')
ib41 = InlineKeyboardButton(text='Казахский', callback_data='kk')
ib42 = InlineKeyboardButton(text='Кхмерский', callback_data='km')
ib43 = InlineKeyboardButton(text='Каннада', callback_data='kn')
ib44 = InlineKeyboardButton(text='Корейский', callback_data='ko')
ib45 = InlineKeyboardButton(text='Киргизский', callback_data='ky')
ib46 = InlineKeyboardButton(text='Латынь', callback_data='la')
ib47 = InlineKeyboardButton(text='Люксембурский', callback_data='lb')
ib48 = InlineKeyboardButton(text='Лаосский', callback_data='lo')
ib49 = InlineKeyboardButton(text='Литовский', callback_data='lt')
ib50 = InlineKeyboardButton(text='Латышский', callback_data='lv')
ib51 = InlineKeyboardButton(text='Малагасийский', callback_data='mg')
ib52 = InlineKeyboardButton(text='Маори', callback_data='mi')
ib53 = InlineKeyboardButton(text='Македонский', callback_data='mk')
ib54 = InlineKeyboardButton(text='Малаялам', callback_data='ml')
ib55 = InlineKeyboardButton(text='Монгольский', callback_data='mn')
ib56 = InlineKeyboardButton(text='Маратхи', callback_data='mr')
ib57 = InlineKeyboardButton(text='Малайский', callback_data='ms')
ib58 = InlineKeyboardButton(text='Мальтийский', callback_data='mt')
ib59 = InlineKeyboardButton(text='Бирманский', callback_data='my')
ib60 = InlineKeyboardButton(text='Непальский', callback_data='ne')
ib61 = InlineKeyboardButton(text='Нидерландский', callback_data='nl')
ib62 = InlineKeyboardButton(text='Норвежский', callback_data='no')
ib63 = InlineKeyboardButton(text='Панджаби', callback_data='pa')
ib64 = InlineKeyboardButton(text='Польский', callback_data='pl')
ib65 = InlineKeyboardButton(text='Португальский', callback_data='pt')
ib66 = InlineKeyboardButton(text='Румынский', callback_data='ro')
ib67 = InlineKeyboardButton(text='Русский', callback_data='ru')
ib68 = InlineKeyboardButton(text='Сингальский', callback_data='si')
ib69 = InlineKeyboardButton(text='Словацкий', callback_data='sk')
ib70 = InlineKeyboardButton(text='Словенский', callback_data='sl')
ib71 = InlineKeyboardButton(text='Албанский', callback_data='sq')
ib72 = InlineKeyboardButton(text='Сербский', callback_data='sr')
ib73 = InlineKeyboardButton(text='Сунданский', callback_data='su')
ib74 = InlineKeyboardButton(text='Шведский', callback_data='sv')
ib75 = InlineKeyboardButton(text='Суахили', callback_data='sw')
ib76 = InlineKeyboardButton(text='Тамильский', callback_data='ta')
ib77 = InlineKeyboardButton(text='Телугу', callback_data='te')
ib78 = InlineKeyboardButton(text='Таджикский', callback_data='tg')
ib79 = InlineKeyboardButton(text='Тайский', callback_data='th')
ib80 = InlineKeyboardButton(text='Тагальский', callback_data='tl')
ib81 = InlineKeyboardButton(text='Турецкий', callback_data='tr')
ib82 = InlineKeyboardButton(text='Татарский', callback_data='tt')
ib83 = InlineKeyboardButton(text='Украинский', callback_data='uk')
ib84 = InlineKeyboardButton(text='Урду', callback_data='ur')
ib85 = InlineKeyboardButton(text='Узбекский', callback_data='uz')
ib86 = InlineKeyboardButton(text='Вьетнамский', callback_data='vi')
ib87 = InlineKeyboardButton(text='Коса', callback_data='xh')
ib88 = InlineKeyboardButton(text='Идиш', callback_data='yi')
ib89 = InlineKeyboardButton(text='Китайский', callback_data='zh')
ikb.add(
    ib67, ib17, ib15, ib19, ib24, ib37, ib38, ib83, ib9, ib10, ib11, ib12, ib13,
    ib14, ib3, ib16, ib2, ib18, ib4, ib20, ib21, ib22, ib23, ib5, ib25,
    ib26, ib27, ib28, ib29, ib30, ib31, ib32, ib33, ib34, ib35, ib36, ib6,
    ib7, ib39, ib40, ib41, ib42, ib43, ib44, ib45, ib46, ib47, ib48, ib49,
    ib50, ib51, ib52, ib53, ib54, ib55, ib56, ib57, ib58, ib59, ib60, ib61,
    ib62, ib63, ib64, ib65, ib66, ib1, ib68, ib69, ib70, ib71, ib72, ib73,
    ib74, ib75, ib76, ib77, ib78, ib79, ib80, ib81, ib82, ib8, ib84, ib85,
    ib86, ib87, ib88, ib89
)

ikb2 = InlineKeyboardMarkup(row_width=2)
ikb2_1 = InlineKeyboardButton(text='Закончить перевод', callback_data='False')
ikb2_2 = InlineKeyboardButton(text='Поменять язык', callback_data='True')
ikb2.add(ikb2_1, ikb2_2)
